apiVersion: apps/v1
kind: Deployment
metadata:
  name: delphinusedgepyapp
  namespace: delphinusedgepyapp
  labels:
    app.kubernetes.io/name: delphinusedgepyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delphinusedgepyapp
  template:
    metadata:
      labels:
        app: delphinusedgepyapp
    spec:
      containers:
        - name: app
          image: k3d-registry.localhost:5500/delphinusedgepyapp:local
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          readinessProbe:
            initialDelaySeconds: 5
            failureThreshold: 60
            periodSeconds: 2
            httpGet:
              path: /readyz
              port: 8080

          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            httpGet:
              path: /healthz
              port: 8080

          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: delphinusedgepyapp
  namespace: delphinusedgepyapp
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: delphinusedgepyapp
