apiVersion: apps/v1
kind: Deployment
metadata:
  name: delphinusedgepyapp
  namespace: delphinusedgepyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delphinusedgepyapp
  template:
    metadata:
      labels:
        app: delphinusedgepyapp
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/delphinusedgepyapp:beta
          imagePullPolicy: Always

          args:
          - --zone
          - west-or-pdx
          - --region
          - west

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
