apiVersion: apps/v1
kind: Deployment
metadata:
  name: csapp
  namespace: csapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csapp
  template:
    metadata:
      labels:
        app: csapp
        buildTag: build-0.0.1-0407-0600
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/csapp:beta
          imagePullPolicy: Always

          args:
          - --zone
          - west-or-pdx
          - --region
          - west

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
