apiVersion: v1
kind: Service
spec:
  type: NodePort
  selector:
    app: {{gitops.name}}
  ports:
    - port: {{gitops.port}}
      targetPort: {{gitops.port}}
      nodePort: {{gitops.nodePort}}

metadata:
  namespace: {{gitops.namespace}}
  labels:
    app: {{gitops.name}}
  name: {{gitops.name}}

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{gitops.name}}-vs
  namespace: {{gitops.namespace}}
spec:
  hosts:
    - "{{gitops.config.domain}}"
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: {{gitops.name}}
            port:
              number: 8080
