apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxmodule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxmodule
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginxmodule
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: nginxmodule
        image: intelligentedge/nginxmodule:0.27.0-amd64
        imagePullPolicy: Always
        ports:
        - containerPort: 8181

---
apiVersion: v1
kind: Service
metadata:
  name: nginxmodule
spec:
  type: LoadBalancer
  ports:
  - port: 8181
  selector:
    app: nginxmodule
