apiVersion: apps/v1
kind: Deployment
metadata:
  name: privateapp
  namespace: privateapp
  labels:
    app.kubernetes.io/name: privateapp
    foo: bar
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: privateapp
  template:
    metadata:
      labels:
        app: privateapp
    spec:
      containers:
        - name: app
          image: ghcr.io/wbreza/imdb-app:v2
          imagePullPolicy: Always
          args:
          - --in-memory
          - --zone
          - wabrez-wa
          - --region
          - wabrez
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: privateapp
  namespace: privateapp
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: privateapp

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: privateapp-vs
  namespace: privateapp
spec:
  hosts:
    - "wabrez-wa-seattle-102.cseretail.com"
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: privateapp
            port:
              number: 8080
