apiVersion: apps/v1
kind: Deployment
metadata:
  name: failover-test
  namespace: failover-test
  labels:
    app.kubernetes.io/name: failover-test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: failover-test
  template:
    metadata:
      labels:
        app: failover-test
    spec:
      containers:
        - name: app
          image: ghcr.io/cse-labs/imdb-app:latest
          imagePullPolicy: Always
          args: 
          - --in-memory
          - --prometheus
          - --zone
          - west-co-denver
          - --region
          - west
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi

---

apiVersion: v1
kind: Service
metadata:
  name: failover-test
  namespace: failover-test
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: failover-test
    
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: failover-test-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`west-co-denver-102.cseretail.com`)
      kind: Rule
      services:
        - name: failover-test
          namespace: failover-test
          kind: Service
          port: 8080
  tls:
    secretName: ssl-cert
