apiVersion: v1
kind: Service
spec:
  type: NodePort
  selector:
    app: testapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

metadata:
  namespace: testapp
  labels:
    app: testapp
  name: testapp

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: testapp-vs
  namespace: testapp
spec:
  hosts:
    - "west-or-pdx-102.cseretail.com"
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
        - uri:
            # The route to match on the externally facing URL
            # Will match requests to https://yourdomain.com/sample and forward requests to to http://app.svc.cluster.local:8080/
            prefix: "/sample"
      rewrite:
        # The path to forward within your application
        # If the match and the rewrite are the same, you can safely remove the rewrite node.
        uri: "/"
      route:
        - destination:
            host: testapp
            port:
              number: 8080
