apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferencemodule
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inferencemodule
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: inferencemodule
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: inferencemodule
        image: intelligentedge/inferencemodule:0.27.0-amd64
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 200m
        env:
          - name: IOTHUB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: azure-env
                key: IOTHUB_CONNECTION_STRING
          - name: IOTEDGE_DEVICE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: azure-env
                key: IOTEDGE_DEVICE_CONNECTION_STRING
          - name: IS_OPENCV
            value: "true"
          - name: IS_K8S
            value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: inferencemodule
  namespace: default
spec:
  ports:
  - port: 5000
  selector:
    app: inferencemodule
