apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-vs
  namespace: default
spec:
  hosts:
    - "central-tx-atx-f01.cseretail.com"
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
      route:
        - destination:
            host: webmodule
            port:
              number: 8000
