apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-vs
  namespace: default
spec:
  hosts:
    - "{{gitops.config.domain}}"
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
      route:
        - destination:
            host: webmodule
            port:
              number: 8000
