apiVersion: v1
kind: Service
spec:
  type: NodePort
  selector:
    app: munishwebapi
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30090

metadata:
  namespace: munishwebapi
  labels:
    app: munishwebapi
  name: munishwebapi

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: munishwebapi-vs
  namespace: munishwebapi
spec:
  hosts:
    - "central-il-chi-101.cseretail.com"
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: munishwebapi
            subset: v1
            port:
              number: 8080
          weight: 50
        - destination:
            host: munishwebapi
            subset: v2
            port:
              number: 8080
          weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: canarytest
  namespace: munishwebapi
spec:
  host: munishwebapi
  subsets:
  - name: v1
    labels:
      app: munishwebapi
  - name: v2
    labels:
      version: v2
