apiVersion: apps/v1
kind: Deployment
metadata:
  name: delphinustest
  namespace: delphinustest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delphinustest
  template:
    metadata:
      labels:
        app: delphinustest
        buildTag: build-0.0.1-0406-1100
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/delphinustest:beta
          imagePullPolicy: Always

          args:
          - --zone
          - east-ny-nyc
          - --region
          - east

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
