global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    origin_prometheus: corp-monitoring-jofultz
remote_write:
- url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
  basic_auth:
    username: "261866"
    password_file: /secrets/prometheus.key
scrape_configs:
  - job_name: 'webv-heartbeat'
    static_configs:
      - targets: [ 'webv-heartbeat:8080' ] # Depends on docker networking dns
    metric_relabel_configs:
    - source_labels: [ __name__ ]
      regex: "WebVDuration_bucket|WebVDuration_sum|WebVSummary_sum"
      action: drop
