apiVersion: apps/v1
kind: Deployment
metadata:
  name: munishwebapi
  namespace: munishwebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: munishwebapi
  template:
    metadata:
      labels:
        app: munishwebapi
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/munishwebapi:beta
          imagePullPolicy: Always

          args:
          - --zone
          - central-india-delhi
          - --region
          - central

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
