apiVersion: v1
kind: Service
spec:
  type: NodePort
  selector:
    app: munishwebapi
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30090

metadata:
  namespace: munishwebapi
  labels:
    app: munishwebapi
  name: munishwebapi

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: munishwebapi-vs
  namespace: munishwebapi
spec:
  hosts:
    - "central-il-chi-102.cseretail.com"
  gateways:
    - istio-system/istio-gateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: munishwebapi
            port:
              number: 8080
