apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngsa-retail-app
  namespace: ngsa
  labels:
    app.kubernetes.io/name: ngsa-retail-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: ngsa-retail-app
  template:
    metadata:
      labels:
        app: ngsa-retail-app
        version: beta-0202-0058
        deploy: 22-02-02-00-58-09
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/retail-edge/retaildemo:v2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: ngsa-retail-app
  namespace: ngsa
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ngsa-retail-app
    
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ngsa-retail-app
  namespace: ngsa
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`retail-app.loblaws.cseretail.com`)
      kind: Rule
      services:
        - name: ngsa-retail-app
          kind: Service
          port: 8080
