apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgeplaygroundpilotapp
  namespace: edgeplaygroundpilotapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgeplaygroundpilotapp
  template:
    metadata:
      labels:
        app: edgeplaygroundpilotapp
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/edgeplaygroundpilotapp:latest
          imagePullPolicy: Always

          args:
          - --zone
          - west-or-pdx
          - --region
          - west

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
