apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-vs
  namespace: {{gitops.namespace}}
spec:
  hosts:
    - "{{gitops.config.domain}}"
  gateways:
    - istio-system/istio-gateway
  http:
    - route:
      - destination:
          host: webmodule
          port:
            number: 8000
