---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-upload
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict  # https://linux.die.net/man/8/mount.cifs
    - nosharesock
  csi:
    driver: file.csi.azure.com
    readOnly: false
    # make sure this volumeid is unique in the cluster
    # `#` is not allowed in self defined volumeHandle
    volumeHandle: upload-volumeid
    volumeAttributes:
      shareName: uploadvolume
    nodeStageSecretRef:
      name: azure-secret
      namespace: default

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-upload
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi
