apiVersion: v1
kind: Service
spec:
  type: NodePort
  selector:
    app: brijwebapi
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

metadata:
  namespace: brijwebapi
  labels:
    app: brijwebapi
  name: brijwebapi

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: brijwebapi-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`east-ny-nyc-102.cseretail.com`)
      kind: Rule
      services:
        - name: brijwebapi
          namespace: brijwebapi
          kind: Service
          port: 8080
  tls:
    secretName: ssl-cert
