apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
  labels:
    app.kubernetes.io/name: {{gitops.name}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: {{gitops.name}}
  template:
    metadata:
      labels:
        app: {{gitops.name}}
    spec:
      containers:
        - name: app
          image: {{gitops.imageName}}:{{gitops.imageTag}}
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          resources:
            limits:
              cpu: 100m
              memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{gitops.name}}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{gitops.name}}
  namespace: {{gitops.namespace}}
spec:
  rules:
  - https:
      paths:
      - path: /heartbeat/
        backend:
          serviceName: {{gitops.name}}
          servicePort: 8080
