kind: Service
apiVersion: v1
metadata:
  name: {{gitops.name}}-nginx
  namespace: ingress
spec:
  type: ExternalName
  externalName: {{gitops.name}}.{{gitops.namespace}}.svc.cluster.local
  ports:
  - port: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{gitops.name}}-ingress
  namespace: ingress

  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'

spec:
  ingressClassName: public

  tls:
    - hosts:
      - '{{gitops.config.domain}}'
      secretName: ssl-cert

  rules:
  - host: '{{gitops.config.domain}}'
    http:
      paths:
      - path: /heartbeat/
        pathType: Prefix
        backend:
          service:
            name: {{gitops.name}}-nginx
            port:
              number: 8080
