apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{gitops.name}}-gateway
  namespace: {{gitops.namespace}}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*.cseretail.com"
      tls:
        httpsRedirect: false
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*.cseretail.com"
      tls:
        mode: SIMPLE
        credentialName: ssl-cert
