apiVersion: v1
kind: Service
spec:
  type: NodePort
  selector:
    app: pilotapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080

metadata:
  namespace: pilotapp
  labels:
    app: pilotapp
  name: pilotapp

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pilotapp-https
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`east-ny-nyc-101.cseretail.com`)
      kind: Rule
      services:
        - name: pilotapp
          namespace: pilotapp
          kind: Service
          port: 8080
  tls:
    secretName: ssl-cert
